### DISCUSSION TITLE
How to move auth_providers to separate integration file

### DISCUSSION THREAD

**Discussion by metbril** [frenck/home-assistant-config#102] [Q&A] [answered]
I'm trying to move my config files to separate files. I currently have:

**configuration.yaml**
```
homeassistant:
  packages: !include_dir_named integrations
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.1.0/24
        - fd00::/8
```

**integrations/homeassistant.yaml**
```
homeassistant:
  customize: !include ../customize.yaml
```

**customize.yaml**
```
sun.sun:
  friendly_name: Zon
```

This is working just fine. The Sun entity is now show as `Zon` in the dashboard.

But when I move the `auth_providers:` section to `integrations/homeassistant.yaml`, the customization file is NOT applied. The Sun entity is shown as 'Sun' in the dashboard.

**NEW configuration.yaml**
```
homeassistant:
  packages: !include_dir_named integrations
```

**NEW integrations/homeassistant.yaml**
```
homeassistant:
  customize: !include ../customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.1.0/24
        - fd00::/8
```

Am I doing something wrong? Or is this a know bug or limitation?
