### ISSUE TITLE
Switches don't show up with multi file in config split

### ISSUE THREAD

**Issue by ezraholm50** [frenck/home-assistant-config#16]
Thanks for sharing your config, has been a great cleanup!

# Problem/Motivation

> Using your package config split, my switches don't work.

## Expected behavior

> A file for every switch would result in the entities showing up in the state tab.

## Actual behavior

> No entities available related to the configured switches, without anything in the logs.

## Steps to reproduce

> See config 
Config that doesnt work

`/config/components/packages/switch.yaml`
```
# This file loads up my switches
#
# https://www.home-assistant.io/components/switch/
#
switch: !include_dir_list ../switches
```

`/config/components/switches/laptop.yaml`
```
platform: template
switches:
  laptop:
    value_template: "{{ is_state('device_tracker.laptop', 'home') }}"
    turn_on:
      service: shell_command.laptop_wol
    turn_off:
      service: shell_command.laptop_suspend
```

`/config/components/switches/pc.yaml`
```
platform: template
switches:
  pc:
    value_template: "{{ is_state('device_tracker.steam', 'home') }}"
    turn_on:
      service: shell_command.steam_wol
    turn_off:
      service: shell_command.steam_suspend
```
-----------------------------------------------
Config that does work (workaround)
`
/config/components/packages/switch.yaml`
```
# This file loads up my switches
#
# https://www.home-assistant.io/components/switch/
#
#switch: !include_dir_list ../switches
switch:
  - platform: template
    switches:
      pc:
        value_template: "{{ is_state('device_tracker.steam', 'home') }}"
        turn_on:
          service: shell_command.steam_wol
        turn_off:
          service: shell_command.steam_suspend
  - platform: template
    switches:
      laptop:
        value_template: "{{ is_state('device_tracker.laptop', 'home') }}"
        turn_on:
          service: shell_command.laptop_wol
        turn_off:
          service: shell_command.laptop_suspend
```

## Proposed changes

> Please advise
