### ISSUE TITLE
Homeassistant[customize] not loading properly as a package.

### ISSUE THREAD

**Issue by manuelbarbosa** [frenck/home-assistant-config#40]
**Homeassistant[customize] not loading properly as a package.**

## What you expected to happen
https://github.com/frenck/home-assistant-config/blob/master/config/integrations/homeassistant.yaml
Should load the customizations for entitites on the `customizations/entities` folder

## What actually happened)
Customizations not beeing applyed at all

## How can someone else make/see it happen
Just load a config with that and add a customization to a entity file on `customizations/entities`

## How will it actually work

```
homeassistant:
  packages: !include_dir_named integrations
  customize: !include ../customize.yaml
```

**Comment by frenck** [comment]
It works really well on my end 🤷

**Comment by robinostlund** [comment]
i have the same issue, not loading at all with latest version of home assistant :/

**Comment by valvanet** [comment]
The "package" **homeassistant:** within _integrations/homeassistant.yaml_ doesn't load the given mappings at all.

for example _configuration.yaml_ : ..
```
homeassistant:
  packages: !include_dir_named integrations
```
.. would load: _integrations/homeassistant.yaml_:

```
homeassistant:
  # Lets me customize individual entities
  customize: !include_dir_merge_named ../customizations/entities

  # Lets me custimize all entities in a domain
  customize_domain: !include_dir_merge_named ../customizations/domains

  # Lets me custimize entities based on a matching pattern
  customize_glob: !include_dir_merge_named ../customizations/globs
```

but the mappings are ignored somehow. so **customize:** wont be recognized at all.

I worked around this issue by moving all mappings to _configuration.yaml_ :
```
homeassistant:
  # Customize.yaml must be mapped in relative root directory
  customize: !include customizations/entities.yaml

  # Load packages
  packages: !include_dir_named integrations

  # Lets me customize individual entities
  customize split: !include_dir_merge_named ../customizations/entities

  # Lets me custimize all entities in a domain
  customize_domain: !include_dir_merge_named ../customizations/domains

  # Lets me custimize entities based on a matching pattern
  customize_glob: !include_dir_merge_named ../customizations/globs
```

I noticed that customizing entities within the GUI is also not possible without using a single .yaml file

If you want to be able to do that, create a file named "entities.yaml" somewhere in your config folder. (e.g. _customizations/entities.yaml_) and link it to **customize:**
```

homeassistant:
  customize: !include customizations/entities.yaml
```

Is there a reason for the mappings not loading from **homeassistant:** if included in **packages:**?
