### ISSUE TITLE
Rewrite Circadian Lighting custom integration

### ISSUE THREAD

**Issue by frenck** [frenck/home-assistant-config#42]
ℹ️ Still need to thing about this all a bit more

# Problem/Motivation

I need a rewrite of the [`Circadian Lighting`](https://github.com/claytonjn/hass-circadian_lighting).

While that custom integration is awesome, it does have its fair share of issues.

For example:

- It can only be configured via YAML.
- Every light or group of lights gets/needs its own circadian light switch.
- The switch toggle the automated lighting adjustments on the lights by the custom integration.
- The entity ID of the switches is not manageable (see: <https://github.com/claytonjn/hass-circadian_lighting/issues/18>)
- When circadian light is switched on, it causes a lot of issues when turning lights off. This is well documented: <https://github.com/claytonjn/hass-circadian_lighting/wiki/Frequently-Asked-Questions#q-why-cant-i-turn-off-my-lights-after-configuring-them-with-circadian-lighting>. Worst part:
  > Unfortunately, there's no good solution to this.

I think the custom integration is sub-optimal, mainly because of large configuration overhead and the last point, causing my lights not to turn off from time to time, which just sucks.

## Proposed changes

The main problem with the circadian lighting integration is the "magic" / automatic handling/control of lights. I'd rather have a service available to manually set a light(s) to the current circadian rhythm.

The advantage of having a service for this, would be:

- No shitload of additional entities to manage
- Can easily decide for each light(s) when to apply the current rhythm, using simple automations
- All features automations have, e.g., with checking conditions apply. This removes the issue with manual control/overrides and turning lights off.

### Implementation

- Simple integration that can be added via the UI.
- Provides sensor entities for the values from the circadian rhythm.
- Provides a single service call.
- Should determine ct/rgb/xy or brightness only to use based on the feature set of a light

### Considerations

- Provide an options in the integration UI, to set global:
  - Min/max brightness
  - Min/max color temp
  - Sunset/Sunrise offsets
  - Update interval for the sensors
  - Default transition value
  - Initial transition when light goes from off -> on

### Service call `circadian.apply`

Simple service call that accepts lights to adjust to the current state of the circadian rhythm.

| Parameter | Optional | Description |
| --- | --- | --- |
| `entity_id` | yes | Entity ID or entities IDs to apply the rhythm to |
| `area` | yes | Area ID to target all lights in an area |
| `transition` | yes | Transition time to apply |
| `auto_brightness` | yes | `boolean`. `true` to adjust brightness, `false` otherwise |
| `min_brightness` | yes | Override from global setting |
| `max_brightness` | yes | Override from global setting |
| `min_colortemp` | yes | Override from global setting |
| `max_colortemp` | yes | Override from global setting |

### Example automation

Simple example:

```yaml
description: Adjust rhythm of garden light
alias: garden_automatic_lighting
id: f59ff023-a412-41b2-946f-8ea05da26c2f
mode: single
trigger:
  - platform: state
    entity_id:
     - light.garden_dining_table
     - sensor.circadian
condition:
  - condition: state
    entity_id: 
      - input_boolean.garden_automatic_lighting
      - light.garden_dining_table
    state: 'on'
action:
  - service: circadian.apply
    entity_id: light.garden_dining_table
```
