### ISSUE TITLE
Waste Collection reminders

### ISSUE THREAD

**Issue by frenck** [frenck/home-assistant-config#46]
# Problem/Motivation

In order not to forget to put the waste bins out on pickup day, I need some sensors, automations and notifications.

## References

- Twente Milieu Integration: https://www.home-assistant.io/integrations/twentemilieu

**Comment by rgruyters** [comment]
Another good one is: https://github.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer

**Comment by WiebKastanje** [comment]
Yes, I'm using this one: https://github.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer
Works great.

**Comment by dtx3k** [comment]
I'm using this with twentemileu https://github.com/heyajohnny/afvalinfo
works very good with minimum of  configuration:
```yaml
sensor:
  - platform: afvalinfo
    resources:
      - gft
      - pbd
      - papier
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    location: hengelo
    postcode: 7550AA
    streetnumber: 100
    dateformat: '%d-%m-%Y'
    locale: 'nl'
    timespanindays: 365
```
big pro are the:   - trash_type_today and -trash_type_tomorrow
these return type of trash as string in the state, or none 

i have 2 automations based upon today or tomorrow, sending me an notification at set times as an reminder
```yaml
-   alias: Alert if and which container needs to go out tomorrow
    trigger: 
      platform: time 
      at: '20:00:00'
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: sensor.afvalinfo_tomorrow
          state: None
    action: 
      - service: notify.HomeNotifier
        data_template:
          message: >
            'Morgen moet de {{ sensor.afvalinfo_tomorrow }} container aan straat, lamme!'

-   alias: Alert if and which container needs to go out today
    trigger: 
      platform: time 
      at: '07:30:00'
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: sensor.afvalinfo_today
          state: None
    action: 
      - service: notify.HomeNotifier
        data_template:
          message: >
            'NU moet de {{ sensor.afvalinfo_today }} container aan straat, wakker worden!'
```
simpel to use, even for me ;) but im shure it can be done more efficient
