### ISSUE TITLE
Consolidate multiple time triggers in automations

### ISSUE THREAD

**Issue by frenck** [frenck/home-assistant-config#48]
# Problem/Motivation

Introduced in: https://github.com/home-assistant/core/pull/37975 (part of Home Assistant 0.114).

Before:

```yaml
automation:
  - alias: time trigger
    trigger:
      - platform: time
        at: "05:00:00"
      - platform: time
        at: "06:00:00"
      - platform: time
        at: "10:00:00"
    action:
      choose:
        ...
```

After:

```yaml
automation:
  - alias: time trigger
    trigger:
      - platform: time
        at:
          - "05:00:00"
          - "06:00:00"
          - "10:00:00"
    action:
      choose:
        ...
```

Or:

```yaml
automation:
  - alias: time trigger
    trigger:
      - platform: time
        at: ["05:00:00", 06:00:00", "10:00:00"]
    action:
      choose:
        ...
```

## Proposed changes

Update all automations with multiple time conditions and merge those triggers into a single trigger.
